# Generated by Django 2.1.8 on 2019-04-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaid', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeAccounts',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'me_accounts',
                'ordering': ('updated',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MePlaidIncome',
            fields=[
                ('income_id', models.AutoField(primary_key=True, serialize=False)),
                ('streams', models.IntegerField(blank=True, null=True)),
                ('last_year_income', models.IntegerField(blank=True, null=True)),
                ('last_year_income_pre_tax', models.IntegerField(blank=True, null=True)),
                ('projected_income', models.IntegerField(blank=True, null=True)),
                ('projected_income_pre_tax', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'me_plaid_income',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MePlaidIncomeStream',
            fields=[
                ('stream_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('monthly_income', models.IntegerField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'me_plaid_income_stream',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MePlaidItemAccountsNumber',
            fields=[
                ('number_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_type', models.CharField(blank=True, max_length=45, null=True)),
                ('account', models.CharField(max_length=100)),
                ('routing', models.CharField(blank=True, max_length=45, null=True)),
                ('wire_routing', models.CharField(blank=True, max_length=45, null=True)),
                ('institution', models.CharField(blank=True, max_length=45, null=True)),
                ('branch', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'me_plaid_item_accounts_number',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MePlaidUserBalanceDetail',
            fields=[
                ('balance_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField()),
                ('temporal_type', models.CharField(max_length=200)),
                ('fetched_date', models.DateField()),
            ],
            options={
                'db_table': 'me_plaid_user_balance_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MePlaidUserIdentity',
            fields=[
                ('user_identity_id', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'me_plaid_user_identity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MePlaidUserItem',
            fields=[
                ('user_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=45)),
                ('item_name', models.CharField(max_length=100)),
                ('accesstoken', models.CharField(max_length=200)),
                ('linked_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'me_plaid_user_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MePlaidUserItemAccounts',
            fields=[
                ('account_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('mask', models.CharField(blank=True, max_length=45, null=True)),
                ('accounts_type', models.CharField(blank=True, max_length=45, null=True)),
                ('subtype', models.CharField(blank=True, max_length=45, null=True)),
                ('official_name', models.CharField(blank=True, max_length=200, null=True)),
                ('available_balance', models.IntegerField(blank=True, null=True)),
                ('iso_currency_code', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'me_plaid_user_item_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MePlaidUserTransactionDetails',
            fields=[
                ('transaction_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
                ('temporal_type', models.CharField(max_length=200)),
                ('fetched_date', models.DateField()),
            ],
            options={
                'db_table': 'me_plaid_user_transaction_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeUserdetail',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(max_length=45)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'me_userdetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlaidIdentityAddress',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('zipcode', models.CharField(max_length=45)),
                ('is_primary', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plaid_identity_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlaidIdentityEmail',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('is_primary', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plaid_identity_email',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlaidIdentityPhone',
            fields=[
                ('phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_type', models.CharField(blank=True, max_length=45, null=True)),
                ('number', models.CharField(blank=True, max_length=45, null=True)),
                ('is_primary', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plaid_identity_phone',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
